apiVersion: 1

datasources:
  - name: Loki
    uid: loki                 # identifiant stable, réutilisable par les dashboards
    type: loki
    access: proxy             # c'est le SERVEUR Grafana qui appelle Loki (pas votre navigateur)
    url: http://loki:3100
    isDefault: true
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090