events {

}

http {
  server {
    listen 80;

    # j'ai pas encore raccordé app1 au réseau, je commente
    location /app1 {
      proxy_pass http://app1:3000;  # hostname sur le reseau du container app1
    }

    location /app2 {
      proxy_pass http://app2;
    }
  }
}
